### ISSUE TITLE
您好,有demo,或者使用方法咩

### ISSUE THREAD

**Issue by Y-A-K-E** [waljqiang/emqtt#1]
另外我mqtt 服务器和php服务器不再一起,请问可以直接用么?

另外看您库里还有一个mqtt库.有啥区别.

**Comment by waljqiang** [comment]
这个只是mqtt的php版客户端，跟mqtt服务器在什么地方没关系，examples里面有使用示例呀，库里面的mqtt库是真实的mqtt实现，外边只是做了方便性的封装而已



waljqiang@163.com
 
发件人： Y.A.K.E
发送时间： 2020-03-15 00:52
收件人： waljqiang/emqtt
抄送： Subscribed
主题： [waljqiang/emqtt] 您好,有demo,或者使用方法咩 (#1)
另外我mqtt 服务器和php服务器不再一起,请问可以直接用么?
另外看您库里还有一个mqtt库.有啥区别.

**Comment by Y-A-K-E** [comment]
好的.谢谢
